ALTER TABLE uploads ADD COLUMN user_agent VARCHAR(512) DEFAULT NULL;

ALTER TABLE accesses ADD COLUMN user_agent VARCHAR(512) DEFAULT NULL;

CREATE TABLE IF NOT EXISTS banned_user_agents (
    pattern VARCHAR(255) NOT NULL PRIMARY KEY,
    reason VARCHAR(255) DEFAULT NULL,
    banned_timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
