CREATE TABLE IF NOT EXISTS blacklist (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    url VARCHAR(255) NOT NULL,
    type TINYINT UNSIGNED NOT NULL DEFAULT 1,
    last_update DATETIME DEFAULT NULL,
    update_interval_seconds BIGINT UNSIGNED NOT NULL DEFAULT 86400
);
